# Generated by Django 3.1.5 on 2021-01-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediatype',
            field=models.CharField(default='image', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='aromas',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Aroma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feels',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Feel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_types',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Skin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='textures',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Texture'),
        ),
    ]
