# Generated by Django 3.1.5 on 2021-01-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_types',
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skin',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Skin'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='aromas',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Aroma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feels',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Feel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='textures',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Texture'),
        ),
    ]
