# Generated by Django 3.1.5 on 2021-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='mediatype',
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(default='image', max_length=200),
        ),
        migrations.AlterField(
            model_name='aroma',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='aromas',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Aroma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feels',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Feel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_types',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Skin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='textures',
            field=models.ManyToManyField(null=True, related_name='products', to='products.Texture'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='texture',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
