# Generated by Django 3.1.5 on 2021-01-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210115_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='mediatype',
            new_name='media_type',
        ),
    ]
